# -*- coding: utf-8 -*-
"""Structured code-reference data for the MONOPOLY.LK project.
Every macro, enum, struct field and per-file function is documented
here so the reference PDF can describe ALL the code.
"""

GAME_CYCLE_NOTE = (
    "Round cadence (from game.c playGame): processLoans, insurance expiry, ageing and "
    "modifier ticks run every round; disasters/inflation/market review every 10; "
    "economic events + regional cards every 15; government regulations every 20."
)

# ---------------------------------------------------------------------------
# Compile-time constants (types.h #defines)
# name, value, category, description
# ---------------------------------------------------------------------------
MACROS = [
    ("MAX_PLAYERS", "4", "Core", "Number of players in the game."),
    ("BOARD_SIZE", "40", "Core", "Number of squares on the board."),
    ("MAX_NAME_LENGTH", "50", "Core", "Buffer size for any name (player, square, group)."),
    ("MAX_ROUNDS", "500", "Core", "Hard cap on game rounds; if reached the game ends with a net-worth comparison."),
    ("START_MONEY", "30000", "Core", "Each player starts with LKR 30,000."),
    ("GO_MONEY", "2000", "Core", "Money collected each time a player passes GO."),
    ("JAIL_BAIL", "300", "Jail", "Cost of paying bail to leave Jail."),
    ("INCOME_TAX_RATE", "15", "Tax", "Base Income Tax rate (%) at game start; drifts with market."),
    ("COMMUNITY_FUND_TAX_RATE", "10", "Tax", "Base Community Development Fund rate (%) at game start."),
    ("MAX_HOUSES", "4", "Buildings", "Maximum houses allowed on one property."),
    ("MAX_HOTELS", "1", "Buildings", "Maximum hotels allowed on one property."),
    ("LOAN_DURATION_ROUNDS", "20", "Bank", "Initial length of a loan in rounds."),
    ("LOAN_INTEREST_RATE", "8", "Bank", "Starting loan interest rate (%), drifts with inflation."),
    ("LOAN_COLLATERAL_PERCENT", "75", "Bank", "Rule-LK 2: max loan is 75% of eligible collateral."),
    ("LOAN_EXTEND_ROUNDS", "10", "Bank", "Rule-LK 5: extending a loan adds 10 rounds."),
    ("MORTGAGE_REPAY_PERCENT", "110", "Bank", "Redeeming a mortgage costs 110% of its value."),
    ("LOAN_INTEREST_MIN", "1", "Bank", "Loan interest can never go below this."),
    ("LOAN_INTEREST_MAX", "25", "Bank", "Loan interest can never exceed this."),
    ("LOAN_INTEREST_STEP", "2", "Bank", "Cards/regulations move loan interest by 2 points."),
    ("TAX_RATE_MAX", "25", "Tax", "Cap on the income tax rate after a regulation raises it."),
    ("HOTEL_LUXURY_TAX_PERCENT", "25", "Tax", "Luxury tax: 25% of a hotel's value."),
    ("MIN_CASH_SAFETY", "1000", "Strategy", "Reserve a player keeps before spending / borrowing."),
    ("MIN_CASH_FLOOR", "500", "Strategy", "Risk Taker's floor before mortgaging."),
    ("TRADER_CASH_FLOOR", "1200", "Strategy", "Opportunistic Trader's mortgage floor."),
    ("COMFORTABLE_CASH", "3000", "Strategy", "Conservative Banker's comfort line."),
    ("BAIL_CASH_SPARE", "1500", "Strategy", "Conservative Banker's bail threshold."),
    ("RICH_CASH_LINE", "5000", "Strategy", "Rich-player threshold for certain decisions."),
    ("EXPENSIVE_PROP_PRICE", "6000", "Strategy", "Price above which the Trader insures a property."),
    ("RAILWAY_RENT_1", "250", "Rent", "Railway rent when owning 1 station (Table 7)."),
    ("RAILWAY_RENT_2", "500", "Rent", "Railway rent when owning 2 stations."),
    ("RAILWAY_RENT_3", "1000", "Rent", "Railway rent when owning 3 stations."),
    ("RAILWAY_RENT_4", "2000", "Rent", "Railway rent when owning all 4 stations."),
    ("UTILITY_RENT_ONE", "4", "Rent", "Utility rent = 4 x dice when owning 1 utility (Table 8)."),
    ("UTILITY_RENT_TWO", "10", "Rent", "Utility rent = 10 x dice when owning both utilities."),
    ("AUCTION_OPENING_DIVISOR", "2", "Auction", "Rule-LK 19: opening bid = asking value / 2."),
    ("AUCTION_BID_INCREMENT", "250", "Auction", "Every bid must raise the price by this many LKR."),
    ("AUCTION_MAX_ROUNDS", "200", "Auction", "Safety limit so bidding always terminates."),
    ("MARKET_REVIEW_EVERY", "10", "Market", "A property market review happens every 10 rounds."),
    ("MARKET_COOLDOWN_ROUNDS", "30", "Market", "A group can't re-trigger boom/decline for 30 rounds."),
    ("PROPERTY_AGE_LIMIT", "50", "Ageing", "Value starts dropping once age passes this (rule-LK 15)."),
    ("DEPRECIATION_STEP", "5", "Ageing", "Depreciation ticks up every 5 rounds past the age limit."),
    ("MAX_DEPRECIATION", "30", "Ageing", "Depreciation is capped at 30%."),
    ("RENOVATION_COST_PERCENT", "10", "Ageing", "Renovation costs 10% of current value (rule-LK 17)."),
    ("RENOVATION_RENT_BOOST", "5", "Ageing", "Renovated base rent rises 5%."),
    ("NEGLECT_ROUNDS", "20", "Ageing", "No maintenance for 20 rounds causes structural damage."),
    ("STRUCTURAL_VALUE_LOSS", "15", "Ageing", "Damaged building loses 15% of its value."),
    ("STRUCTURAL_RENT_LOSS", "25", "Ageing", "Damaged building loses 25% of its rent."),
    ("DAMAGE_REPAIR_MULTIPLIER", "150", "Ageing", "Fixing structural damage costs 150% of replacement value."),
    ("REPAIR_COST_PERCENT", "30", "Insurance", "Disaster repairs cost 30% of a property's value."),
    ("PREMIUM_BASIC_PERCENT", "5", "Insurance", "Basic insurance premium = 5% of value."),
    ("PREMIUM_COMPREHENSIVE_PERCENT", "10", "Insurance", "Comprehensive premium = 10% of value."),
    ("PREMIUM_INTERRUPTION_PERCENT", "15", "Insurance", "Business Interruption premium = 15% of value."),
    ("INSURANCE_DURATION_ROUNDS", "20", "Insurance", "A policy lasts 20 rounds."),
    ("INSURANCE_RENEW_AT", "10", "Insurance", "Renew when 10 or fewer rounds remain."),
    ("INSURANCE_EXPIRY_WARNING", "3", "Insurance", "Warn 3 rounds before a policy expires."),
    ("DISASTER_WEIGHT", "20", "Insurance", "Every disaster is equally likely at base weight 20."),
    ("DISASTER_BOOST", "30", "Insurance", "Weather/unrest makes one disaster type +30 likely."),
    ("BI_LOST_INCOME_ROUNDS", "5", "Insurance", "Business Interruption: no rent for 5 rounds."),
    ("JAIL_SQUARE", "10", "Jail", "Board index of the Jail square."),
    ("JAIL_MAX_TURNS", "3", "Jail", "After this many failed turns in Jail, bail is forced."),
    ("EVENT_CARD_COUNT", "20", "Events", "Number of National Event Cards (0..19)."),
    ("ECONOMIC_EVENT_COUNT", "8", "Events", "Number of random economic events."),
    ("REGULATION_COUNT", "8", "Events", "Number of government regulations."),
    ("REGIONAL_CARD_COUNT", "12", "Events", "Number of Regional Development Cards (Table 4)."),
    ("ECONOMY_CYCLE", "10", "Events", "Disasters, inflation and market review every 10 rounds."),
    ("EVENT_CYCLE", "15", "Events", "Economic events + regional cards every 15 rounds."),
    ("REGULATION_CYCLE", "20", "Events", "Government regulations every 20 rounds."),
    ("MAX_UNDEVELOPED_PROPS", "3", "Anti-Spec", "Anti-Speculation Act: at most 3 undeveloped properties."),
    ("ANTI_SPEC_TRIGGER_ROUNDS", "5", "Anti-Spec", "Forced sale after 5 consecutive rounds over the limit."),
    ("MAX_MODIFIERS", "48", "Economy", "Capacity of the modifiers[] array in Economy."),
]

MACRO_CATEGORIES = [
    ("Core", "CORE CONSTANTS"),
    ("Jail", "JAIL RULES"),
    ("Tax", "TAXES"),
    ("Buildings", "BUILDINGS"),
    ("Bank", "BANK & LOANS"),
    ("Strategy", "STRATEGY THRESHOLDS"),
    ("Rent", "RENT TABLES"),
    ("Auction", "AUCTION RULES"),
    ("Market", "MARKET REVIEW"),
    ("Ageing", "AGEING & DEPRECIATION"),
    ("Insurance", "INSURANCE & DISASTERS"),
    ("Events", "EVENT CADENCES & DECKS"),
    ("Anti-Spec", "ANTI-SPECULATION ACT"),
    ("Economy", "MODIFIER ECONOMY"),
]

# ---------------------------------------------------------------------------
# Enums (types.h)
# type, value, description
# ---------------------------------------------------------------------------
ENUMS = {
    "SquareType": [
        ("GO", "Starting square; passing it pays GO_MONEY."),
        ("PROPERTY", "An ownable colour property (developable)."),
        ("RAILWAY", "An ownable railway; rent depends on number owned."),
        ("UTILITY", "An ownable utility; rent depends on dice roll."),
        ("TAX", "Income Tax square."),
        ("COMMUNITY_FUND", "Community Development Fund square."),
        ("EVENT", "National Event Card square."),
        ("BANK", "Bank of Ceylon square (loans)."),
        ("INSURANCE", "Insurance square (policies)."),
        ("JAIL", "Jail / Just Visiting."),
        ("FREE_PARKING", "Do nothing."),
        ("GO_TO_JAIL", "Sent to Jail."),
    ],
    "PropertyGroup": [
        ("BROWN", "Brown properties (Pettah, Maradana)."),
        ("LIGHT_BLUE", "Light Blue (Bambalapitiya, Wellawatte, Mount Lavinia)."),
        ("PINK", "Pink (Nugegoda, Maharagama, Kottawa)."),
        ("ORANGE", "Orange (Negombo, Katunayake, Ja-Ela)."),
        ("RED", "Red (Kandy City, Peradeniya, Katugastota)."),
        ("YELLOW", "Yellow (Galle Fort, Unawatuna, Hikkaduwa)."),
        ("GREEN", "Green (Jaffna Town, Nallur, Trincomalee)."),
        ("DARK_BLUE", "Dark Blue (Nuwara Eliya, Galle Face)."),
        ("NO_GROUP", "Sentinel = number of real groups; also used as an array bound."),
    ],
    "PlayerType": [
        ("AGGRESSIVE_INVESTOR", "Player 1. Buys to complete monopolies."),
        ("CONSERVATIVE_BANKER", "Player 2. Avoids risk and debt."),
        ("RISK_TAKER", "Player 3. Spends everything; insures only after a loss."),
        ("OPPORTUNISTIC_TRADER", "Player 4. Buys cheap, sells into declines."),
    ],
    "InsuranceType": [
        ("NO_INSURANCE", "No policy."),
        ("BASIC_INSURANCE", "Covers Fire and Flood; pays 80%."),
        ("COMPREHENSIVE_INSURANCE", "Covers all disasters; pays 100%."),
        ("BUSINESS_INTERRUPTION", "Covers all; 100% + 5 rounds of lost income."),
    ],
    "DisasterType": [
        ("FIRE", "Fire damage."),
        ("FLOOD", "Flood damage."),
        ("RIOT", "Riot damage."),
        ("BUILDING_COLLAPSE", "Structural collapse."),
        ("ELECTRICAL_FAILURE", "Electrical failure."),
    ],
    "ModifierType": [
        ("MOD_VALUE_GLOBAL", "All property values."),
        ("MOD_GROUP_VALUE", "One colour group's property values."),
        ("MOD_INDEX_VALUE", "A single square's value (any type)."),
        ("MOD_RAIL_VALUE", "All railway values."),
        ("MOD_PURCHASE_PRICE", "Direct purchase prices."),
        ("MOD_RENT_GLOBAL", "All rent."),
        ("MOD_GROUP_RENT", "One colour group's rent."),
        ("MOD_HOTEL_RENT", "Hotel rent."),
        ("MOD_RAIL_RENT", "Railway rent."),
        ("MOD_UTIL_RENT", "Utility rent."),
        ("MOD_CONSTRUCTION", "House/hotel construction costs."),
        ("MOD_INSURANCE", "Insurance premiums."),
        ("MOD_MARKET_MORTGAGE", "Mortgage values."),
        ("MOD_AUCTION_PRICE", "Auction starting prices."),
        ("MOD_FLOOD_RISK", "Flood more likely (Heavy Monsoon)."),
        ("MOD_RIOT_RISK", "Riot more likely (Political Unrest)."),
        ("MOD_BI_CLAIMS", "BI claims inflated (Political Unrest)."),
        ("MOD_RECESSION", "Strategy flag for Economic Recession."),
    ],
    "ModifierSource": [
        ("SRC_GENERAL", "Events, national cards, government regulations."),
        ("SRC_BOOM", "Property Market Review - booming group."),
        ("SRC_DECLINE", "Property Market Review - declining group."),
        ("SRC_REGIONAL", "Regional Development Card."),
    ],
}

# ---------------------------------------------------------------------------
# Structs (types.h)
# struct -> list of (field, type, description)
# ---------------------------------------------------------------------------
STRUCTS = {
    "Loan": [
        ("active", "int", "1 when the player has an outstanding loan (only one loan at a time)."),
        ("amount", "int", "Current outstanding balance in LKR (grows with compound interest)."),
        ("interestRate", "int", "Annual/round interest rate the loan is charged at."),
        ("remainingRounds", "int", "Rounds left before foreclosure."),
    ],
    "Property": [
        ("name", "char[]", "Property display name (echoed into the Square name too)."),
        ("group", "PropertyGroup", "Colour group (BROWN..DARK_BLUE)."),
        ("purchasePrice", "int", "Base price to buy (inflation and modifiers can move this)."),
        ("mortgageValue", "int", "Value received when mortgaging (redeem costs +10%)."),
        ("baseRent", "int", "Rent with zero houses (Table multipliers on top)."),
        ("houseCost", "int", "Cost of building one house."),
        ("hotelCost", "int", "Cost of building a hotel."),
        ("owner", "int", "Player index who owns it; -1 means unowned."),
        ("houses", "int", "Number of houses (0..4)."),
        ("hotel", "int", "1 if a hotel is built (replaces the 4 houses)."),
        ("mortgaged", "int", "1 if the property is mortgaged (no rent until redeemed)."),
        ("loanLocked", "int", "1 if the property is pledged as loan collateral (cannot be sold)."),
        ("insurance", "InsuranceType", "Currently held policy type."),
        ("insuranceRoundsLeft", "int", "Rounds remaining on the current policy."),
        ("damaged", "int", "1 after a disaster until repaired (no rent)."),
        ("repairCostOwed", "int", "Remaining repair cost after insurance compensation."),
        ("lostIncomeRoundsLeft", "int", "Business Interruption: rounds with no rent."),
        ("age", "int", "Rounds since purchase/last renovation."),
        ("depreciation", "int", "Percent value loss from age (0..30%)."),
        ("condition", "int", "Building condition 0..100 (Table 3 rent mapping)."),
        ("roundsSinceMaintenance", "int", "Rounds since last maintenance."),
        ("structurallyDamaged", "int", "1 when neglect (20+ rounds) caused structural damage."),
        ("preDamagePurchasePrice", "int", "Purchase price before structural damage (for restore)."),
        ("preDamageBaseRent", "int", "Base rent before structural damage (for restore)."),
        ("maintenanceCostMultiplierPercent", "int", "Cost multiplier (150% after damage, else 100%)."),
    ],
    "Square": [
        ("index", "int", "Board position 0..39."),
        ("type", "SquareType", "What this square is (GO, PROPERTY, ...)."),
        ("name", "char[]", "Square display name."),
        ("property", "Property", "The embedded property data used by all square kinds."),
    ],
    "Player": [
        ("name", "char[]", "Strategy name (Aggressive Investor, etc.)."),
        ("strategy", "PlayerType", "Which strategy drives every decision."),
        ("position", "int", "Current board position 0..39."),
        ("cash", "int", "Cash balance in LKR."),
        ("inJail", "int", "1 while in Jail."),
        ("jailTurns", "int", "Consecutive jail turns while failing to roll doubles."),
        ("bankrupt", "int", "1 once the player is out of the game."),
        ("propertiesOwned", "int", "Count of colour properties owned."),
        ("railwaysOwned", "int", "Count of railways owned."),
        ("utilitiesOwned", "int", "Count of utilities owned."),
        ("loan", "Loan", "The player's (single) loan."),
        ("sufferedLoss", "int", "1 after an uninsured disaster (Risk Taker now insures)."),
        ("antiSpecRounds", "int", "Consecutive rounds over the 3-undeveloped limit."),
    ],
    "ActiveModifier": [
        ("type", "ModifierType", "What the modifier affects (value, rent, ...)."),
        ("group", "int", "Colour group if GROUP-scoped, else -1."),
        ("index", "int", "Square index if INDEX-scoped, else -1."),
        ("percent", "int", "Multiplier percent (100 = no change, 120 = +20%)."),
        ("roundsLeft", "int", "Rounds until the modifier expires."),
        ("source", "ModifierSource", "Origin used by Rule-LK 36 reporting (boom/decline/regional/general)."),
    ],
    "Economy": [
        ("inflationRate", "int", "Current inflation percent (-3..12) applied every 10 rounds."),
        ("loanInterestRate", "int", "Current economy loan interest rate (1..25)."),
        ("constructionSuspendedRoundsLeft", "int", "Labour Strike blocks building while > 0."),
        ("closedPropertyIndex", "int", "Square closed by Political Rally (-1 none)."),
        ("closedPropertyRoundsLeft", "int", "Rounds the closed property stays closed."),
        ("incomeTaxRate", "int", "Current income tax rate (base 15, can rise via regulation)."),
        ("antiSpeculationActive", "int", "1 once the Anti-Speculation regulation fires."),
        ("currentCardIndex", "int", "Position in the National Event Card deck (0..19)."),
        ("groupCooldownUntilRound", "int[]", "Per group: earliest round it may boom/decline again."),
        ("lastBoomGroup", "int", "Group boosted by the most recent market review."),
        ("lastDeclineGroup", "int", "Group declined by the most recent market review."),
        ("modifiers", "ActiveModifier[]", "Array of up to 48 active timed modifiers."),
        ("modifierCount", "int", "How many modifiers are currently active."),
    ],
    "GameState": [
        ("board", "Square[]", "The 40 squares of the board."),
        ("players", "Player[]", "The 4 players."),
        ("economy", "Economy", "Shared economy state (inflation, modifiers, decks)."),
    ],
}

# ---------------------------------------------------------------------------
# Per-file function documentation.
# Each file: (short_name, overview, intro_heading, [functions])
# Function keys: name, sig, purpose, params [(name, desc)...], ret,
#                locals [(name, desc)...], logic []
# ---------------------------------------------------------------------------
MODULES = [
# ============================ board.c ============================
("board.c",
 "Board construction. Creates the 40 squares of the Sri Lanka themed board in initializeBoard, using four helper setters. It is the first module called by the game.",
 [("initializeBoard", "void initializeBoard(GameState game[])",
   "Builds the complete 40-square board: special squares, 4 railways, 2 utilities and every colour property, using the helper setters.",
   [], "void - the board is written into game[0].board.",
   [("(none)", "All data reaches the board via the setter calls.")],
   ["Lays out special squares at their fixed indices (GO=0, Income Tax=4, Jail=10, Go To Jail=30, Bank=38, etc.).",
    "Places 4 railways, 2 utilities, then every colour property in groups of two (Brown, Dark Blue) or three.",
    "Each property is given real Sri Lankan city names and prices/rents that increase with the colour group."]),
   ("setProperty", "void setProperty(GameState game[], int index, char name[], PropertyGroup group, int purchasePrice, int baseRent, int mortgageValue, int houseCost, int hotelCost)",
   "Fills in one colour property square with its trade economics and resets ownership/build state.",
   [("index", "Board position."),
    ("name", "Display name."),
    ("group", "Colour group of the property."),
    ("purchasePrice", "Base purchase price in LKR."),
    ("baseRent", "Rent with no houses."),
    ("mortgageValue", "Mortgage value."),
    ("houseCost", "Cost of one house."),
    ("hotelCost", "Cost of a hotel.")],
   "void.",
   [("(none)", "Sets fields directly.")],
   ["Copies the name into both the Square name and the embedded Property name.",
    "Zeroes owner (-1 = unowned), houses, hotel, mortgage, loan-lock, insurance, damage, age, depreciation, condition (=100), and structural-damage state so an uninitialized GameState never leaves garbage."]),
   ("setRailway", "void setRailway(GameState game[], int index, char name[], int purchasePrice)",
   "Creates a railway square. Mortgage value is fixed at half the purchase price.",
   [("index", "Board position."),
    ("name", "Station name."),
    ("purchasePrice", "Price to buy.")],
   "void.",
   [("(none)", "")],
   ["Type is RAILWAY; baseRent/houseCost/hotelCost are zeroed (railways can't be developed).",
    "Condition and ageing fields are still initialized so shared property logic never reads uninitialized data."]),
   ("setUtility", "void setUtility(GameState game[], int index, char name[], int purchasePrice)",
   "Creates a utility square (mortgage = half price), same zeroing discipline as railways.",
   [("index", "Board position."),
    ("name", "Utility name."),
    ("purchasePrice", "Price to buy.")],
   "void.",
   [("(none)", "")],
   ["Type is UTILITY, rent tables use the dice roll at landing time instead of stored base rent."]),
   ("setSpecialSquare", "void setSpecialSquare(GameState game[], int index, SquareType type, char name[])",
   "Creates a non-ownable square (GO, Tax, Jail, ...).",
   [("index", "Board position."),
    ("type", "SquareType of the special square."),
    ("name", "Display name.")],
   "void.",
   [("(none)", "")],
["Critical: owner must be set to -1. A zero-filled GameState would otherwise make the square look owned by Player 0.",
     "Only the fields that special-square logic reads are initialized."]),
]),

# ============================ players.c ============================
("players.c",
 "The 4 AI strategies. Every decision a player makes funnels through a should*/wants* function that switches on the player's strategy. This is the behavioural brain of the simulation.",
 [("initializePlayers", "void initializePlayers(GameState game[])",
   "Names the four players and gives their starting state.",
   [], "void.",
   [("i", "Loop index over MAX_PLAYERS.")],
   ["Assigns the four fixed names and strategy tags in order.",
    "Position 0, cash = START_MONEY, all counters zero, loan cleared via resetLoan, sufferedLoss and antiSpecRounds = 0."]),
   ("shouldBuyProperty", "int shouldBuyProperty(GameState game[], int playerIndex)",
   "Decides whether the player buys the square they just landed on.",
   [("playerIndex", "The deciding player.")],
   "1 = buy, 0 = pass.",
   [("price", "Purchase price after market modifiers."),
    ("position", "Current board square.")],
   ["Prices are matched to what buyProperty actually charges: PROPERTY uses currentMarketValue x MOD_PURCHASE_PRICE.",
    "Aggressive Investor: buys if it completes a monopoly, else keeps 1000 reserve.",
    "Conservative Banker: refuses property during recession (MOD_RECESSION active), else keeps half its cash.",
    "Risk Taker: buys anything it can afford.",
    "Opportunistic Trader: never buys into a declining group (group value < 100), only buys at <= 40% of cash."]),
   ("shouldConstruct", "int shouldConstruct(GameState game[], int playerIndex, int cost, int isHotel)",
   "Decides whether the player spends on a house/hotel now.",
   [("playerIndex", "The deciding player."),
    ("cost", "Construction cost."),
    ("isHotel", "1 when the building is a hotel.")],
   "1 = build, 0 = don't.",
   [("cash", "Player's cash.")],
   ["Aggressive Investor: keeps MIN_CASH_SAFETY (1000) reserve.",
    "Conservative Banker: never builds a hotel while a loan is active; otherwise keeps half cash.",
    "Risk Taker: builds anything it can afford.",
    "Opportunistic Trader: builds eagerly when construction is subsidised (< 100%), delays while inflation pushes costs up, otherwise keeps 40%."]),
   ("wantsLoan", "int wantsLoan(GameState game[], int playerIndex)",
   "Whether the player wants to take out a new loan (Bank visit, no current loan).",
   [("playerIndex", "The deciding player.")],
   "1 = wants a loan, 0 = doesn't.",
   [("cash", "Player's cash.")],
   ["Aggressive Investor and Risk Taker always want a loan.",
    "Conservative Banker only borrows when bankrupt-close (cash < MIN_CASH_SAFETY).",
    "Opportunistic Trader borrows below RICH_CASH_LINE (5000)."]),
   ("wantsToRepayLoan", "int wantsToRepayLoan(GameState game[], int playerIndex)",
   "Whether the player repays the loan (fully) during a Bank visit.",
   [("playerIndex", "The deciding player.")],
   "1 = repay in full, 0 = keep the loan.",
   [("cash", "Player's cash."),
    ("loanAmount", "Outstanding loan balance.")],
   ["Aggressive Investor: repay once cash >= 2x loan.",
    "Conservative Banker: repay once cash >= loan.",
    "Risk Taker: rarely repays, needs cash >= 5x loan.",
    "Opportunistic Trader: repay once cash >= 1.5x loan."]),
   ("wantsIncreaseLoan", "int wantsIncreaseLoan(GameState game[], int playerIndex)",
   "Rule-LK 5: borrow more against newly acquired collateral during a Bank visit.",
   [("playerIndex", "The deciding player.")],
   "1 = increase the loan, 0 = don't.",
   [("cash", "Player's cash.")],
   ["Aggressive Investor and Risk Taker always increase.",
    "Conservative Banker below COMFORTABLE_CASH (3000); Opportunistic Trader below RICH_CASH_LINE (5000)."]),
   ("wantsExtendLoan", "int wantsExtendLoan(GameState game[], int playerIndex)",
   "Rule-LK 5: extend the loan term by 10 rounds.",
   [("playerIndex", "The deciding player.")],
   "1 = extend, 0 = don't.",
   [("remainingRounds", "Rounds left on the loan."),
    ("cash", "Player's cash."),
    ("loanAmount", "Outstanding balance.")],
   ["Aggressive Investor prefers borrowing more over extending (never extends).",
    "Conservative Banker extends if <= 5 rounds left and can't afford to repay.",
    "Risk Taker extends when <= 10 rounds left; Opportunistic Trader when <= 5."]),
   ("wantsRefinance", "int wantsRefinance(GameState game[], int playerIndex)",
   "Rule-LK 5: refinance at the economy's current (lower) rate.",
   [("playerIndex", "The deciding player.")],
   "1 = refinance, 0 = don't.",
   [("(none)", "Reads the economy rate and the loan's rate.")],
   ["Refinance only makes sense when the current economy rate is strictly lower than the loan's rate."]),
   ("desiredInsurance", "InsuranceType desiredInsurance(GameState game[], int playerIndex, int propIndex)",
   "Returns the policy type the player wants for a given property.",
   [("playerIndex", "The deciding player."),
    ("propIndex", "The property being considered.")],
   "InsuranceType for the policy.",
   [("hasHotel", "Whether the property has a hotel."),
    ("purchasePrice", "Property base purchase price.")],
   ["Aggressive Investor: Comprehensive on hotels, Basic otherwise.",
    "Conservative Banker: always Comprehensive.",
    "Risk Taker: nothing until it suffered a loss; then Business Interruption on hotels, Basic otherwise.",
    "Opportunistic Trader: Comprehensive only on expensive properties (>= EXPENSIVE_PROP_PRICE), else none."]),
   ("shouldRenovateAgeDepreciation", "int shouldRenovateAgeDepreciation(GameState game[], int playerIndex, int depreciationPercent)",
   "Whether the player pays to renovate away age depreciation.",
   [("playerIndex", "The deciding player."),
    ("depreciationPercent", "Current depreciation of the property.")],
   "1 = renovate, 0 = don't.",
   [("(none)", "Switch on strategy.")],
   ["Conservative Banker renovates at >= 10% depreciation; Opportunistic Trader at >= 15%; everyone else at >= 20%."]),
   ("shouldMaintain", "int shouldMaintain(GameState game[], int playerIndex, int condition, int cost)",
   "Whether the player performs maintenance on a building.",
   [("playerIndex", "The deciding player."),
    ("condition", "Current building condition."),
    ("cost", "Maintenance cost.")],
   "1 = maintain, 0 = don't.",
   [("cash", "Player's cash.")],
   ["Risk Taker only fixes when condition < 25 (unavoidable).",
    "Everyone else maintains when the cost leaves >= 20% of cash free."]),
   ("willingToBid", "int willingToBid(GameState game[], int playerIndex, int propIndex, int candidateBid)",
   "Whether the player raises the bid at an auction.",
   [("playerIndex", "The deciding player."),
    ("propIndex", "Property being auctioned."),
    ("candidateBid", "Next bid amount.")],
   "1 = bid, 0 = withdraw from this auction for good.",
   [("marketValue", "Current market value of the property.")],
   ["Must be able to afford the bid (cash >= candidateBid).",
    "Aggressive Investor: bid up to 120% of market value.",
    "Conservative Banker: only below market value.",
    "Risk Taker: bids anything.",
    "Opportunistic Trader: only up to 80% of market value."]),
   ("shouldMortgage", "int shouldMortgage(GameState game[], int playerIndex)",
   "Whether the player mortgages a property.",
   [("playerIndex", "The deciding player.")],
   "1 = mortgage, 0 = don't.",
   [("cash", "Player's cash.")],
   ["Conservative Banker below COMFORTABLE_CASH; Risk Taker below MIN_CASH_FLOOR; Aggressive Investor below MIN_CASH_SAFETY; Opportunistic Trader below TRADER_CASH_FLOOR."]),
   ("shouldRedeemMortgage", "int shouldRedeemMortgage(GameState game[], int playerIndex, int redeemCost)",
   "Whether the player redeems a mortgaged property.",
   [("playerIndex", "The deciding player."),
    ("redeemCost", "110% of the mortgage value.")],
   "1 = redeem, 0 = don't.",
   [("(none)", "Uses redeemCost parameter.")],
   ["Redeems only when it can afford to pay the cost and still keep at least the same amount (cash - cost >= cost)."]),
   ("shouldPayBail", "int shouldPayBail(GameState game[], int playerIndex)",
   "Whether the player pays bail after failing to roll doubles.",
   [("playerIndex", "The deciding player.")],
   "1 = pay bail, 0 = stay in Jail and keep rolling.",
   [("cash", "Player's cash.")],
   ["Conservative Banker pays when cash >= BAIL_CASH_SPARE (1500).",
    "Risk Taker never pays (prefers to roll).",
    "Aggressive Investor / Opportunistic Trader pay when cash >= RICH_CASH_LINE (5000)."]),
]),

# ============================ game.c ============================
("game.c",
 "The game engine: turn loop, dice, movement, Jail, round bookkeeping, turn-order resolution and the winner. playGame holds the master loop, playTurn resolves one player's landing.",
 [("startGame", "void startGame(GameState game[])",
   "Entry point driven by main.c: seeds RNG, initialises everything, runs the game and prints results.",
   [], "void.",
   [("turnOrder", "Resulting order of play."),
    ("moneyBuffer", "Formatted START_MONEY.")],
   ["Seeds srand with time(NULL), then calls initializeBoard, initializePlayers, initEconomy and initMarket.",
    "Determines turn order, calls playGame, then displays final results."]),
   ("playGame", "void playGame(GameState game[], int turnOrder[])",
   "Master loop. A round completes only when EVERY solvent player has passed GO at least once (not after one turn each).",
   [("turnOrder", "Player order fixed by the opening rolls.")],
   "void.",
   [("round", "Current round 1..MAX_ROUNDS."),
    ("turnPointer", "Cycles through turnOrder."),
    ("playerIndex", "Current player."),
    ("passedGoThisRound", "Per-player flag that GO was crossed this round."),
    ("i", "Loop index."),
    ("allPassed", "Whether every solvent player crossed GO."),
    ("passedGo", "Return of playTurn for the current player.")],
   ["While round <= 500: the current player takes a turn; if they passed GO, mark it.",
    "Once all solvent players have passed GO, run the round-end batch: processLoans, processInsuranceExpiry, ageProperties, ageBuildings, decrementEventTimers, decrementModifiers, enforceAntiSpeculation.",
    "Cycle-based events: every 10 rounds triggerDisaster + applyInflation + reviewPropertyMarket; every 15 triggerEconomicEvent + drawRegionalCard; every 20 triggerGovernmentRegulation.",
    "Display round summary + market conditions; end early when only one solvent player remains."]),
   ("playTurn", "int playTurn(GameState game[], int playerIndex)",
   "One whole turn for one player (Rule 3): repair/maintain, handle jail, roll, move, resolve landing, build, sell declining, mortgage.",
   [("playerIndex", "The active player.")],
   "1 if the player passed GO during the turn, else 0.",
   [("dice", "Dice roll 2..12."),
    ("pos", "Position after moving."),
    ("passedGo", "GO-crossed flag."),
    ("jailResult", "Return of handleJail."),
    ("squareType", "Type of the square landed on.")],
   ["Bankrupt players skip the turn entirely.",
    "Step 1: tryAutoRepair, performMaintenance, renovateStructuralDamage fix buildings first.",
    "If in Jail: handleJail returns 1 and no move happens this turn.",
    "Else roll dice, movePlayer (collects GO money), then resolve landing by square type (property/railway/util -> payRent+buyProperty, EVENT, TAX, COMMUNITY_FUND, GO_TO_JAIL, BANK, INSURANCE).",
    "Step 6: constructBuildings; then sellDecliningProperties; then handleMortgageDecisions."]),
   ("movePlayer", "int movePlayer(GameState game[], int playerIndex, int dice)",
   "Advances the player; collects GO money if they passed or landed on GO.",
   [("playerIndex", "The moving player."),
    ("dice", "Movement amount.")],
   "1 if the player passed GO, else 0.",
   [("oldPosition", "Position before moving."),
    ("passedGo", "Flag."),
    ("moneyBuffer", "Formatted GO_MONEY.")],
   ["position = (oldPosition + dice) % BOARD_SIZE.",
    "If old + dice >= BOARD_SIZE the player passed GO: receive GO_MONEY and print the collection."]),
   ("rollDice", "int rollDice(void)",
   "Rolls two six-sided dice and returns the sum.",
   [], "Sum 2..12.",
   [("die1", "First die 1..6."),
    ("die2", "Second die 1..6.")],
   ["Uses rand() % 6 + 1 for each die (srand was seeded once at startGame)."]),
   ("handleJail", "int handleJail(GameState game[], int playerIndex)",
   "Resolves a Jail turn. Returns 1 when the player is in jail (their turn ends), 0 when they take a normal turn.",
   [("playerIndex", "The jailed (or not) player.")],
   "0 = not in jail; 1 = was in jail (released or not).",
   [("die1", "First die."),
    ("die2", "Second die.")],
   ["Not in jail -> return 0 immediately.",
    "Roll doubles -> released (free), but no move this turn (Rule 13).",
    "Failed doubles -> strategy-driven bail if affordable (releases, no move).",
    "Otherwise jailTurns++ ; at JAIL_MAX_TURNS (3) bail is forced and the player is released.",
    "All releases keep the player ON the Jail square this turn."]),
   ("resolveGroup", "int resolveGroup(GameState game[], int groupPlayers[], int groupSize, int output[], int startIndex)",
   "Resolves a group of (possibly tied) players into a strict order by rolling dice, recursing on ties.",
   [("groupPlayers", "Indices of players to order."),
    ("groupSize", "How many are in this group."),
    ("output", "Order filled in from startIndex."),
    ("startIndex", "Where to write into output.")],
   "How many players were written.",
   [("rolls", "Each tied player's roll."),
    ("i, j, temp", "Sorting indices / swap."),
    ("runStart, runLength", "Start and length of an equal-roll run."),
    ("tiedPlayers", "Re-rolled subset on a tie."),
    ("written", "Count written so far."),
    ("k", "Copies the tied group.")],
   ["Every player rolls once; sort descending by roll (bubble sort).",
    "Walk the sorted list: a single roll is placed directly; an equal run recurses on just those players until all ties are broken."]),
   ("determineTurnOrder", "void determineTurnOrder(GameState game[], int turnOrder[])",
   "Finds who plays first and the full order of play.",
   [("turnOrder", "Output order array.")],
   "void.",
   [("allPlayers", "All 4 player indices."),
    ("i", "Loop index.")],
   ["Seeds allPlayers = {0,1,2,3}, calls resolveGroup on all of them, and announces who begins."]),
   ("countHouses", "int countHouses(GameState game[], int playerIndex)",
   "Counts houses (not hotels) owned by a player.",
   [("playerIndex", "The player.")],
   "Number of houses 0..many.",
   [("i", "Board index."),
    ("count", "Running total.")],
   ["Sums property.houses over PROPERTY squares owned by the player that don't have a hotel."]),
   ("countHotels", "int countHotels(GameState game[], int playerIndex)",
   "Counts hotels owned by a player.",
   [("playerIndex", "The player.")],
   "Number of hotels.",
   [("i", "Board index."),
    ("count", "Running total.")],
   ["Counts PROPERTY squares owned with property.hotel == 1."]),
   ("displayRoundSummary", "void displayRoundSummary(GameState game[], int round)",
   "Prints every player's cash, net worth, properties, buildings, loan and bankrupt status.",
   [("round", "Round number.")],
   "void.",
   [("i", "Player index."),
    ("cashBuf, netBuf, loanBuf", "Formatted LKR strings.")],
   ["Uses formatLKR for cash/net worth/loan, countHouses/countHotels for the building counts."]),
   ("countSolventPlayers", "int countSolventPlayers(GameState game[])",
   "Counts players who are not bankrupt.",
   [], "Number of solvent players.",
   [("i", "Player index."),
    ("count", "Running total.")],
   ["Loops all players and counts !bankrupt."]),
   ("determineWinner", "int determineWinner(GameState game[])",
   "Finds the winner: the last solvent player, or the highest net worth at round 500 (Rule 15).",
   [], "Winner's player index.",
   [("i", "Player index."),
    ("winner", "Best player so far."),
    ("bestNetWorth", "Best net worth so far."),
    ("netWorth", "Current candidate's net worth.")],
   ["Iterates solvent players keeping the highest net worth.",
    "Edge case: if everyone is bankrupt at once, compares net worth across ALL players anyway."]),
   ("displayFinalResults", "void displayFinalResults(GameState game[])",
   "Prints the winner's cash/property/loan/net worth and every player's final standing.",
   [], "void.",
   [("winner", "determineWinner result."),
    ("i", "Player index."),
    ("cashBuf, propBuf, loanBuf, netBuf", "Formatted values.")],
   ["Property value = calculatePropertyValue + calculateBuildingValue."]),
]),

# ============================ finance.c ============================
("finance.c",
 "The economic core (largest file). Ownership, money movement, rent, buying, mortgages, taxes, building (Rule 9), net worth and the Anti-Speculation Act.",
 [("stripOwnership", "void stripOwnership(GameState game[], int index)",
   "Resets a square to unowned: no owner, mortgage, loan pledge or insurance.",
   [("index", "Square to reset.")],
   "void.",
   [("(none)", "")],
   ["Used by sales, foreclosure and bankruptcy liquidation. Does not clear buildings - callers do that with demolishBuildingsOn."]),
   ("resetLoan", "void resetLoan(GameState game[], int playerIndex)",
   "Wipes a player's loan (active, amount, rate, rounds).",
   [("playerIndex", "The player.")],
   "void.",
   [("(none)", "")],
   ["Used at game start and after full repayment / foreclosure."]),
   ("adjustOwnedCount", "void adjustOwnedCount(GameState game[], int playerIndex, int index, int delta)",
   "Updates the player's owned counter to match the square's type.",
   [("playerIndex", "The player."),
    ("index", "Square whose owner changed."),
    ("delta", "+1 for a buy, -1 for a loss.")],
   "void.",
   [("(none)", "")],
   ["PROPERTY -> propertiesOwned, RAILWAY -> railwaysOwned, UTILITY -> utilitiesOwned."]),
   ("groupOf", "PropertyGroup groupOf(GameState game[], int index)",
   "Returns the colour group of a square, or -1 if it isn't a property.",
   [("index", "Square index.")],
   "PropertyGroup, or (PropertyGroup)-1.",
   [("(none)", "")],
   ["Used on rails/utilities too - they return -1 so group-scoped maths ignores them."]),
   ("receiveMoney", "void receiveMoney(GameState game[], int playerIndex, int amount)",
   "Adds money to a player, but only if they are not bankrupt.",
   [("playerIndex", "Receiver."),
    ("amount", "Amount in LKR.")],
   "void.",
   [("(none)", "")],
   ["The bankrupt check is important: bankrupt players take no further part, so GO and rent must not revive them."]),
   ("payMoney", "void payMoney(GameState game[], int playerIndex, int amount)",
   "Subtracts money, escaping bankruptcy: a Risk Taker first sells its cheapest undeveloped property; if still negative the player is bankrupt and assets are liquidated.",
   [("playerIndex", "Payer."),
    ("amount", "Amount in LKR.")],
   "void.",
   [("before", "Count of undeveloped properties before the sale.")],
   ["Risk Taker loop: while cash < 0 and not bankrupt and strategy == RISK_TAKER, sell the cheapest undeveloped property; break if a sale didn't reduce the count (all remaining are loan-locked).",
    "If still negative after the loop, mark bankrupt, print the announcement, liquidate assets, then clamp cash to 0."]),
   ("liquidateBankruptAssets", "void liquidateBankruptAssets(GameState game[], int playerIndex)",
   "Rule 14: on bankruptcy, demolishes buildings and auctions every owned square.",
   [("playerIndex", "The bankrupt player.")],
   "void.",
   [("i", "Board index.")],
   ["Clears the loan, then for every owned square: demolishBuildingsOn, stripOwnership, clear damage, adjustOwnedCount(-1) and runAuction with no seller."]),
   ("payTax", "void payTax(GameState game[], int playerIndex)",
   "Income Tax: currentTaxRatePercent(INCOME_TAX_RATE) x net worth.",
   [("playerIndex", "The taxpayer.")],
   "void.",
   [("rate", "Effective tax rate."),
    ("netWorth", "Net worth (can be negative for a broke player)."),
    ("amount", "Tax owed.")],
   ["Clamps amount at 0 - a tax must never pay a player (bug fix)."]),
   ("payCommunityFundTax", "void payCommunityFundTax(GameState game[], int playerIndex)",
   "Community Development Fund: currentTaxRatePercent(COMMUNITY_FUND_TAX_RATE) x property (land) value, not buildings.",
   [("playerIndex", "The taxpayer.")],
   "void.",
   [("rate", "Effective rate."),
    ("assets", "calculatePropertyValue result."),
    ("amount", "Tax owed.")],
   ["Only land counts: assets come from calculatePropertyValue which excludes buildings."]),
   ("findPropertyToMortgage", "int findPropertyToMortgage(GameState game[], int playerIndex)",
   "Finds the first mortgageable owned property.",
   [], "Square index, or -1 if none.",
   [("i", "Board index.")],
   ["Skips non-owned, already mortgaged, loan-locked, and developed (houses/hotel) properties."]),
   ("findMortgagedProperty", "int findMortgagedProperty(GameState game[], int playerIndex)",
   "Finds the first mortgaged owned property.",
   [], "Square index, or -1 if none.",
   [("i", "Board index.")],
   ["Checks owner and mortgaged flag."]),
   ("mortgageProperty", "void mortgageProperty(GameState game[], int playerIndex)",
   "Mortgages the first eligible property if the strategy wants to.",
   [("playerIndex", "The player.")],
   "void.",
   [("propIndex", "Chosen property."),
    ("payout", "Mortgage value after market modifier."),
    ("group", "The property's group for MOD_MARKET_MORTGAGE.")],
   ["Payout = mortgageValue x modifierMultiplier(MOD_MARKET_MORTGAGE, group) - booming groups +15%, declining -10% (Rule-LK 34).",
    "Sets mortgaged = 1 and receives the payout."]),
   ("redeemMortgage", "void redeemMortgage(GameState game[], int playerIndex)",
   "Redeems the first mortgaged property at 110% of value.",
   [("playerIndex", "The player.")],
   "void.",
   [("propIndex", "Chosen mortgaged property."),
    ("redeemCost", "110% of mortgage value.")],
   ["Only acts if the strategy wants to and the player can afford the cost."]),
   ("handleMortgageDecisions", "void handleMortgageDecisions(GameState game[], int playerIndex)",
   "The turn-end mortgage step: try redeeming first, then mortgaging.",
   [("playerIndex", "The player.")],
   "void.",
   [("(none)", "")],
   ["Redeem is attempted before mortgage so a player never mortgages and immediately redeems."]),
   ("calculateRent", "int calculateRent(GameState game[], int position)",
   "Rent for a normal property from Table 6 (houses/hotel), scaled by group/global/hotel modifiers and building condition (Table 3).",
   [("position", "The square.")],
   "Rent in LKR.",
   [("rent", "Running rent."),
    ("conditionPercent", "Table 3 mapping."),
    ("houses", "Houses on the property."),
    ("hotel", "Hotel flag."),
    ("baseRent", "Base rent."),
    ("group", "The property's group."),
    ("condition", "Building condition.")],
   ["Multipliers: 0 houses x1, x2, x3, x5, x7; hotel x10.",
    "Then x MOD_GROUP_RENT x MOD_RENT_GLOBAL, and x MOD_HOTEL_RENT if a hotel.",
    "Developed buildings also scale by rentConditionPercent(condition) - excellent 100% down to closed 0%."]),
   ("calculateRailwayRent", "int calculateRailwayRent(GameState game[], int playerIndex)",
   "Railway rent from Table 7 based on how many stations the OWNER has, scaled by rail/global rent modifiers.",
   [("playerIndex", "The railway owner.")],
   "Rent in LKR.",
   [("i", "Board index."),
    ("count", "Number of owned stations."),
    ("baseRent", "Table lookup by count.")],
   ["Uses the owner's count (passed the owner index, not the square)."]),
   ("calculateUtilityRent", "int calculateUtilityRent(GameState game[], int playerIndex, int diceValue)",
   "Utility rent from Table 8: dice x 4 (one utility) or dice x 10 (both), scaled by util/global modifiers.",
   [("playerIndex", "The utility owner."),
    ("diceValue", "The roll that just happened.")],
   "Rent in LKR.",
   [("i", "Board index."),
    ("count", "Owned utilities."),
    ("rent", "Running rent.")],
   ["Only uses the dice value, so it must be called from payRent with the landing dice."]),
   ("groupSize", "int groupSize(GameState game[], PropertyGroup group)",
   "How many squares belong to a colour group.",
   [("group", "The group.")],
   "Count (2 or 3 in this board).",
   [("i", "Board index."),
    ("count", "Running total.")],
   ["Counts PROPERTY squares whose group == group."]),
   ("ownsMonopoly", "int ownsMonopoly(GameState game[], int playerIndex, PropertyGroup group)",
   "Whether the player owns every member of the group.",
   [("playerIndex", "The player."),
    ("group", "The group.")],
   "1 = full monopoly, 0 = not.",
   [("i", "Board index."),
    ("owned", "Count owned by the player.")],
   ["owned == groupSize(group)."]),
   ("developGroup", "int developGroup(GameState game[], int playerIndex, PropertyGroup group)",
   "Builds one house (or the group's hotel) keeping development even (Rule 9). Returns 1 if anything was built.",
   [("playerIndex", "The player."),
    ("group", "The group to develop.")],
   "1 = built, 0 = nothing built.",
   [("i", "Board index."),
    ("minHouses", "Fewest houses among eligible members."),
    ("targetIndex", "The property to build on."),
    ("allFourHouses", "1 when every unblocked member has 4 houses (hotel allowed)."),
    ("hotelCost", "Modified hotel cost."),
    ("houseCost", "Modified house cost."),
    ("costBuf", "Formatted cost.")],
   ["Only runs on full monopolies.",
    "Blocked member (mortgaged/damaged/loan-locked) that isn't fully developed prevents the whole group's hotel (Rule 9).",
    "Always adds to the property with the fewest houses; never exceeds 4 houses on one property (Rule 9 bug fix).",
    "Builds a hotel when allFourHouses is true; costs are scaled by MOD_CONSTRUCTION (group-scoped so a boom's +10% only hits its own group).",
    "Strategy decision via shouldConstruct before paying."]),
   ("constructBuildings", "void constructBuildings(GameState game[], int playerIndex)",
   "Builds the maximum affordable buildings in one turn by repeatedly calling developGroup per group.",
   [("playerIndex", "The player.")],
   "void.",
   [("group", "Iterates BROWN..DARK_BLUE."),
    ("builtSomething", "Whether the last developGroup call built."),
    ("safetyLimit", "Protects against an endless build loop.")],
   ["Skips everything while constructionSuspendedRoundsLeft > 0 (Labour Strike).",
    "Per group, keeps calling developGroup until it returns 0 or a 20-call safety limit is hit."]),
   ("calculatePropertyValue", "int calculatePropertyValue(GameState game[], int playerIndex)",
   "Total current market value of owned, unmortgaged squares.",
   [("playerIndex", "The player.")],
   "Value in LKR.",
   [("i", "Board index."),
    ("total", "Running total.")],
   ["Uses currentMarketValue for railways/utilities too so their value modifiers apply.",
    "Mortgaged properties contribute 0."]),
   ("calculateBuildingValue", "int calculateBuildingValue(GameState game[], int playerIndex)",
   "Cash value of all houses and hotels.",
   [("playerIndex", "The player.")],
   "Value in LKR.",
   [("i", "Board index."),
    ("total", "Running total.")],
   ["Hotel -> hotelCost; houses -> houses x houseCost."]),
   ("calculateNetWorth", "int calculateNetWorth(GameState game[], int playerIndex)",
   "Rule 15 net worth: cash + property + buildings - outstanding loan.",
   [("playerIndex", "The player.")],
   "Net worth in LKR.",
   [("cash", "Player's cash."),
    ("propertyValue", "calculatePropertyValue."),
    ("buildingValue", "calculateBuildingValue."),
    ("outstandingLoans", "Active loan balance or 0.")],
   ["Used by taxes, round summaries, the winner and the final table."]),
   ("countUndevelopedProperties", "int countUndevelopedProperties(GameState game[], int playerIndex)",
   "Counts owned colour properties with no houses and no hotel.",
   [("playerIndex", "The player.")],
   "Count.",
   [("i", "Board index."),
    ("count", "Running total.")],
   ["The Anti-Speculation Act's core metric."]),
   ("wouldCompleteMonopoly", "int wouldCompleteMonopoly(GameState game[], int playerIndex, int pos)",
   "True if buying the square at pos would complete a whole colour group.",
   [("playerIndex", "The player."),
    ("pos", "The square being considered.")],
   "1 = completes a monopoly, 0 = not.",
   [("i", "Board index."),
    ("group", "Target group.")],
   ["Contributes to the Aggressive Investor's buying rule."]),
   ("sellLowValueProperty", "void sellLowValueProperty(GameState game[], int playerIndex)",
   "Sells the player's cheapest undeveloped property to the Bank at market value (Risk Taker bankruptcy tactic).",
   [("playerIndex", "The player.")],
   "void.",
   [("i", "Board index."),
    ("best", "Cheapest property."),
    ("bestValue", "Its market value."),
    ("value", "Current candidate's value.")],
   ["Skips developed, loan-locked property (Rule-LK 3 - collateral can never be sold).",
    "Receives market value, strips ownership, adjusts count."]),
   ("sellDecliningProperties", "void sellDecliningProperties(GameState game[], int playerIndex)",
   "Opportunistic Trader dumps undeveloped property in groups currently declining, under a global downturn, or with a negative index modifier.",
   [("playerIndex", "The player.")],
   "void.",
   [("i", "Board index."),
    ("globalMult", "MOD_VALUE_GLOBAL multiplier."),
    ("groupMult", "This group's MOD_GROUP_VALUE."),
    ("indexMult", "This square's MOD_INDEX_VALUE."),
    ("value", "Sell price.")],
   ["Only for OPPORTUNISTIC_TRADER who isn't bankrupt.",
    "Sells when any of the three multipliers is under 100 (i.e. in decline).",
    "Never sells developed or loan-locked properties."]),
   ("sellUndevelopedPropertyToAuction", "void sellUndevelopedPropertyToAuction(GameState game[], int playerIndex)",
   "Anti-Speculation Act: releases the player's lowest-value undeveloped property and auctions it.",
   [("playerIndex", "The player.")],
   "void.",
   [("i", "Board index."),
    ("best", "Cheapest undeveloped property."),
    ("bestValue", "Its market value."),
    ("value", "Candidate value.")],
   ["Skips developed and loan-locked property; the seller keeps the auction proceeds (sellerIndex = playerIndex)."]),
   ("forceSellExcess", "void forceSellExcess(GameState game[], int playerIndex)",
   "Sells excess undeveloped property until the player is back at the 3-property limit.",
   [("playerIndex", "The player.")],
   "void.",
   [("excess", "Count above the limit."),
    ("before", "Count before a sale (to detect stalls).")],
   ["Breaks if a sale doesn't reduce the count (everything left is loan-locked), guaranteeing termination."]),
   ("enforceAntiSpeculation", "void enforceAntiSpeculation(GameState game[])",
   "Rule-LK 8: once active, force-auctions excess undeveloped property after 5 consecutive rounds over the limit.",
   [], "void.",
   [("i", "Player index."),
    ("undeveloped", "Player's undeveloped property count.")],
   ["If the act is off, reset every player's antiSpecRounds and return.",
    "Per player: over the limit -> antiSpecRounds++, and when it reaches 5 force the sale and reset; at/under the limit -> reset the counter."]),
   ("buyProperty", "void buyProperty(GameState game[], int playerIndex)",
   "Handles landing on an unowned square: prices it, asks the strategy, buys or sends to auction.",
   [("playerIndex", "The player.")],
   "void.",
   [("pos", "Current square."),
    ("price", "Price after modifiers."),
    ("wantsToBuy", "Strategy decision."),
    ("priceBuf, balanceBuf", "Formatted values.")],
   ["Only acts on unowned PROPERTY/RAILWAY/UTILITY.",
    "PROPERTY price = currentMarketValue x MOD_PURCHASE_PRICE (group-scoped, boom +15%). Rails/utilities use currentMarketValue directly.",
    "If the strategy declines or cash is short, the property goes to auction (Rule 5).",
    "On purchase: payMoney, set owner, increment the right owned counter."]),
   ("payRent", "void payRent(GameState game[], int playerIndex, int diceValue)",
   "Resolves rent when landing on an owned, unmortgaged, working square.",
   [("playerIndex", "The player who landed."),
    ("diceValue", "The roll, for utility rent.")],
   "void.",
   [("pos", "Current square."),
    ("owner", "The square's owner."),
    ("rent", "Computed rent."),
    ("rentBuf", "Formatted rent.")],
   ["Landed on your own property -> no rent; tries renovation for aged property.",
    "No rent if unowned, mortgaged, closed by Political Rally, damaged, or in Business Interruption.",
    "PROPERTY/RAILWAY/UTILITY dispatch to the three rent calculators.",
    "payMoney(tenant) and receiveMoney(owner)."]),
]),

# ============================ bank.c ============================
("bank.c",
 "Loans, collateral and foreclosure. Rule-LK 2 (75% collateral loan), Rule-LK 5 (Bank visit actions) and Rule-LK 6/7 (foreclosure) live here.",
 [("groupBasePrice", "int groupBasePrice(GameState game[], PropertyGroup group)",
   "The base price of a colour group - the first property's purchase price - used ONLY for loan collateral maths.",
   [("group", "The group.")],
   "Base price in LKR, 0 for no match.",
   [("i", "Board index.")],
   ["Reads straight from the board (first PROPERTY in the group) instead of storing a duplicate constant.",
    "Rail/utility are not part of this - they use their own mortgage value."]),
   ("totalEligibleCollateral", "int totalEligibleCollateral(GameState game[], int playerIndex)",
   "Sum of the player's unmortgaged, un-pledged property values (group base price for colour property, mortgage value for rail/utility), each x its market modifier.",
   [("playerIndex", "The player.")],
   "Collateral value in LKR.",
   [("i", "Board index."),
    ("total", "Running total."),
    ("group", "Property's group."),
    ("mult", "MOD_MARKET_MORTGAGE multiplier.")],
   ["Skips non-ownable, non-owned, mortgaged and loan-locked squares.",
    "Booming groups' collateral +15%, declining -10% (Rule-LK 34)."]),
   ("calculateMaxLoan", "int calculateMaxLoan(GameState game[], int playerIndex)",
   "Rule-LK 2: the maximum loan = 75% of eligible collateral.",
   [("playerIndex", "The player.")],
   "Max loan in LKR.",
   [("(none)", "Delegates to totalEligibleCollateral.")],
   ["Pure formula function: collateral x LOAN_COLLATERAL_PERCENT / 100."]),
   ("obtainLoan", "void obtainLoan(GameState game[], int playerIndex)",
   "Takes a new loan: locks every eligible property as collateral and pays out the max loan at the current rate.",
   [("playerIndex", "The player.")],
   "void.",
   [("i", "Board index."),
    ("maxLoan", "Amount borrowed."),
    ("loanBuf", "Formatted amount.")],
   ["Only one active loan per player at a time.",
    "Locked = collateral pledge (loanLocked=1) blocks selling/mortgaging (Rule-LK 3).",
    "20 rounds at the economy's current interest rate."]),
   ("repayLoan", "void repayLoan(GameState game[], int playerIndex, int amount)",
   "Repays part or all of the loan; on full repayment all collateral is released.",
   [("playerIndex", "The player."),
    ("amount", "Amount to repay.")],
   "void.",
   [("i", "Board index.")],
   ["Clamps the payment to the loan balance and to the player's cash.",
    "On a zero balance: resetLoan and clear every loanLocked flag."]),
   ("handleBankVisit", "void handleBankVisit(GameState game[], int playerIndex)",
   "The Bank square: repay full / increase / extend / refinance (existing loan), or obtain a new loan (Strategy 3.5). One transaction per visit.",
   [("playerIndex", "The player.")],
   "void.",
   [("repayAmount", "Amount to repay (always the full loan).")],
   ["With a loan, follows the preference chain: full repay (strategy), increase, extend, refinance.",
    "Without a loan, obtains one if the strategy wants it."]),
   ("increaseLoan", "void increaseLoan(GameState game[], int playerIndex)",
   "Rule-LK 5: borrows 75% of collateral acquired since the loan was taken out.",
   [("playerIndex", "The player.")],
   "void.",
   [("i", "Board index."),
    ("availableCollateral", "Value of new eligible collateral."),
    ("additional", "Extra amount borrowed.")],
   ["Only when a loan is active; finds unmortgaged, un-pledged property.",
    "Adds the extra amount, locks the new collateral, pays out via receiveMoney."]),
   ("extendLoan", "void extendLoan(GameState game[], int playerIndex)",
   "Rule-LK 5: adds 10 rounds to the loan deadline.",
   [("playerIndex", "The player.")],
   "void.",
   [("(none)", "")],
   ["Guarded on an active loan."]),
   ("refinanceLoan", "void refinanceLoan(GameState game[], int playerIndex)",
   "Rule-LK 5: switches the loan to the economy's current rate.",
   [("playerIndex", "The player.")],
   "void.",
   [("(none)", "")],
   ["Only beneficial when the current economy rate is lower (strategy decides)."]),
   ("demolishBuildingsOn", "void demolishBuildingsOn(GameState game[], int index)",
   "Zeroes houses and hotel on a property (used on seizure and bankruptcy).",
   [("index", "The square.")],
   "void.",
   [("(none)", "")],
   ["Condition and damage flags are left alone - callers manage those."]),
   ("foreclose", "void foreclose(GameState game[], int playerIndex)",
   "Rule-LK 6/7: a defaulted loan seizes and auctions every pledged property; the player is bankrupt if nothing is left.",
   [("playerIndex", "The player.")],
   "void.",
   [("i", "Board index."),
    ("ownsAnythingLeft", "1 if any non-pledged property remains.")],
   ["Every loanLocked property is demolished, stripped, count-adjusted and auctioned.",
    "Non-pledged property keeps the player solvent.",
    "If nothing is left and cash <= 0, the player is bankrupt."]),
   ("processLoans", "void processLoans(GameState game[])",
   "Round-end loan heartbeat: compounds interest into the principal and counts down; at 0 rounds, forecloses.",
   [], "void.",
   [("i", "Player index."),
    ("interest", "Round interest amount.")],
   ["Interest = amount x rate%, written back into amount (compounding).",
    "remainingRounds-- , and at <= 0 foreclose."]),
]),

# ============================ auction.c ============================
("auction.c",
 "The auction engine (Rule-LK 19-23). Used when nobody buys directly and for forced sales (Anti-Speculation Act, bankruptcy, foreclosure).",
 [("getAskingValue", "int getAskingValue(GameState game[], int propIndex)",
   "Rule-LK 19/32/34: asking value = current market value x auction modifier (declining groups start -25%).",
   [("propIndex", "The square.")],
   "Asking value in LKR.",
   [("value", "Current market value."),
    ("group", "The square's group (may be -1).")],
   ["Applies MOD_AUCTION_PRICE scoped to the group, so only the declining group's auction price drops."]),
   ("runAuction", "void runAuction(GameState game[], int propIndex, int sellerIndex)",
   "Sells a property to the highest bidder among solvent players. Opening = value/2, bids rise by 250, passers are out forever. The forced seller never bids.",
   [("propIndex", "The square being auctioned."),
    ("sellerIndex", "Forced seller (>= 0) who receives the money, or -1 for the Bank.")],
   "void.",
   [("active", "Per-player in/out flag."),
    ("activeCount", "Players still bidding."),
    ("i", "Loop index."),
    ("currentBid", "Current highest bid."),
    ("highBidder", "Leader, or -1."),
    ("candidateBid", "Next proposed bid."),
    ("safetyRounds", "Loop guard."),
    ("moneyBuf", "Formatted bid."),
    ("remaining", "Last active bidder when only one remains."),
    ("lastActive", "Finder of the last active bidder.")],
   ["Opening bid = askingValue / 2.",
    "Bankrupt players are out; the forced seller is excluded (bug fix) so they can't 'pay themselves' (net-zero) and defeat the forced sale.",
    "While more than one bids: each active player either raises by 250 or withdraws permanently; capped at 200 safety rounds.",
    "Single remaining bidder gets one final chance; if nobody bids at all, or the last bidder declines the opening price, the property stays with the Bank.",
    "Winner pays, the seller (if any) receives it, ownership transfers."]),
]),

# ============================ events.c ============================
("events.c",
 "Cards and regulations: 20 national event cards, 8 economic events (every 15 rounds) and 8 government regulations (every 20 rounds), plus interest clamping and timer decrementing.",
 [("clampLoanInterest", "void clampLoanInterest(GameState game[])",
   "Keeps the loan interest rate inside [1, 25].",
   [], "void.",
   [("(none)", "Mutates economy.loanInterestRate.")],
   ["Called after any change to the rate."]),
   ("adjustLoanInterest", "void adjustLoanInterest(GameState game[], int deltaPercent)",
   "Moves the loan interest rate by deltaPercent and clamps it.",
   [("deltaPercent", "Signed change, e.g. -2 or +2.")],
   "void.",
   [("(none)", "")],
   ["Rate = rate + delta; then clampLoanInterest."]),
   ("executeEvent", "void executeEvent(GameState game[], int playerIndex)",
   "Draws the current National Event Card (0..19, cycling like draw-top-put-bottom). Effects are global, so playerIndex is unused.",
   [("playerIndex", "Unused - effects are global, not per-player.")],
   "void.",
   [("candidates, count, i", "Owned properties for Political Rally case 3."),
    ("group, groupBuffer", "Random group for Property Revaluation case 16."),
    ("lucky", "Solvent grant recipient for case 18.")],
   ["Tourism Hype (0) hotels x2 rent 5r; Fuel Shortage (1) rail rent x2 5r; Heavy Floods (2) disaster; Political Rally (3) closes a random owned property 2r; Stock Market Rise (4) values +10% 15r; Economic Downturn (5) values -15% 15r; Housing Subsidy (6) construction -30% 15r; Interest Cut/Rise (7/8) +/-2 points; Tax Amnesty (9) +2000 to everyone; Power Failure (10) utility rent /2 3r; Foreign Funding (11) Orange values +15% 15r; Port Expansion (12) rail values +20% 15r; Festival Season (13) hotel rent +50% 5r; Labour Strike (14) construction suspended 2r; Insurance Discount (15) premiums -20% 10r; Property Revaluation (16) random group +15% 15r; Currency Depreciation (17) construction +10% 15r; Government Grant (18) 5000 to a SOLVENT player (bug fix - never a bankrupt one); National Disaster (19) disaster.",
    "Advances currentCardIndex = (index + 1) % 20 after drawing."]),
   ("triggerEconomicEvent", "void triggerEconomicEvent(GameState game[])",
   "One of 8 random economy-wide events every 15 rounds (Tourism Boom, Fuel Crisis, Heavy Monsoon, Economic Recession, Stock Market Boom, Government Housing, Foreign Investment, Political Unrest).",
   [], "void.",
   [("choice", "rand() % 8.")],
   ["Each event adds timed modifiers; the recession also applies a +15% loan-interest move, and several events boost disaster risks."]),
   ("triggerGovernmentRegulation", "void triggerGovernmentRegulation(GameState game[])",
   "One of 8 random government regulations every 20 rounds (Property Tax raise, Loan Interest cut, Housing Subsidy, Luxury Property Tax on hotels, Railway Modernization, Electricity Tariff, Insurance Regulation, Anti-Speculation Act).",
   [], "void.",
   [("choice", "rand() % 8."),
    ("tax", "Luxury tax for one hotel."),
    ("i", "Board index.")],
   ["Case 3 (Luxury Tax) bills 25% of each hotel's market value, printed per owner/property (bug fix).",
    "Case 7 activates the Anti-Speculation Act economy-wide."]),
   ("decrementEventTimers", "void decrementEventTimers(GameState game[])",
   "Ticks the non-modifier event timers down: construction suspension and the closed property.",
   [], "void.",
   [("(none)", "Mutates economy fields.")],
   ["Modifier timers are decremented separately (decrementModifiers)."]
),
]),

# ============================ economy.c ============================
("economy.c",
 "Inflation, the modifier economy, ageing and maintenance. currentMarketValue is the single 'real price' function reused across the whole game.",
 [("initEconomy", "void initEconomy(GameState game[])",
   "Resets all economy state: zero inflation, base rates, empty modifier list.",
   [], "void.",
   [("(none)", "")],
   ["Loan interest = LOAN_INTEREST_RATE, tax = INCOME_TAX_RATE, card index 0, no modifiers, anti-spec off, no closed property."]),
   ("applyRate", "int applyRate(int oldValue, int ratePercent)",
   "Rule-LK 14: applies a percentage change, never returning below 1.",
   [("oldValue", "Starting value."),
    ("ratePercent", "Signed percent (-3, +8, ...).")],
   "New value (>= 1).",
   [("newValue", "Computed value.")],
   ["newValue = oldValue + oldValue x rate/100; clamped at 1. Used by inflation and interest moves."]),
   ("addSourcedModifier", "void addSourcedModifier(GameState game[], ModifierType type, int group, int index, int percent, int roundsLeft, ModifierSource source)",
   "Appends a timed modifier to the economy, tagging its source for Rule-LK 36 reporting.",
   [("type", "What it affects."),
    ("group", "Group scope or -1."),
    ("index", "Index scope or -1."),
    ("percent", "Multiplier (100 = no change)."),
    ("roundsLeft", "Duration."),
    ("source", "SRC_GENERAL/BOOM/DECLINE/REGIONAL.")],
   "void.",
   [("(none)", "Writes into modifiers[modifierCount].")],
   ["Ignores the add when modifierCount == MAX_MODIFIERS (48)."]),
   ("addModifier", "void addModifier(GameState game[], ModifierType type, int group, int index, int percent, int roundsLeft)",
   "addSourcedModifier with SRC_GENERAL (default for events/cards/regulations).",
   [("type", "What it affects."),
    ("group", "Group scope or -1."),
    ("index", "Index scope or -1."),
    ("percent", "Multiplier."),
    ("roundsLeft", "Duration.")],
   "void.",
   [("(none)", "Delegates.")],
   ["Convenience wrapper - market and regional calls use the sourced version."]),
   ("modifierMultiplier", "int modifierMultiplier(GameState game[], ModifierType type, int group, int index)",
   "Multiplies every matching active modifier together (Rule-LK 34) - so two +25% are roughly +56%.",
   [("type", "Modifier kind."),
    ("group", "Requested group (-1 = any)."),
    ("index", "Requested index (-1 = any).")],
   "Combined multiplier, 100 = no change.",
   [("mult", "Running product."),
    ("i", "Modifier index.")],
   ["A stored group == -1 is global and matches every requested group; likewise for index. Matching modifiers chain-multiply."]),
   ("isModifierActive", "int isModifierActive(GameState game[], ModifierType type, int group, int index)",
   "Whether at least one matching flag-style modifier (flood risk, recession, BI claims) is active.",
   [("type", "Modifier kind."),
    ("group", "Group scope or -1."),
    ("index", "Index scope or -1.")],
   "1 = active, 0 = not.",
   [("i", "Modifier index.")],
   ["Returns at the first exact match - used to gate weighted disasters and strategy decisions."]),
   ("currentTaxRatePercent", "int currentTaxRatePercent(GameState game[], int baseRate)",
   "The effective tax rate: base rate scaled by MOD_VALUE_GLOBAL.",
   [("baseRate", "Base rate (15 or 10).")],
   "Effective percent.",
   [("(none)", "Delegates to modifierMultiplier.")],
   ["Used by both Income Tax and Community Fund purposes."]),
   ("decrementModifiers", "void decrementModifiers(GameState game[])",
   "Ticks every active modifier down and compacts out expired ones.",
   [], "void.",
   [("i", "Scan index."),
    ("j", "Compaction shift.")],
   ["In-place: when roundsLeft <= 0 the array is shifted left, otherwise i advances."]),
   ("formatLKR", "void formatLKR(int amount, char out[])",
   "Formats an amount with thousands separators, e.g. 30000 -> \"30,000\".",
   [("amount", "Raw integer."),
    ("out", "Destination buffer.")],
   "void (writes into out).",
   [("digits", "Plain digits."),
    ("len", "Digit count."),
    ("i", "Digit index."),
    ("w", "Writer index."),
    ("neg", "Negative flag.")],
   ["Inserts a comma every 3 digits from the right and preserves a leading '-'."]),
   ("applyInflation", "void applyInflation(GameState game[])",
   "Every 10 rounds picks a random rate {-3, 0, 2, 5, 8, 12} and applies it to purchase prices, mortgage values, rents, construction costs and the loan interest rate.",
   [], "void.",
   [("possibleRates", "The draw set."),
    ("rate", "Chosen rate."),
    ("i", "Board index.")],
   ["Uses applyRate on every ownable square's price/mortgage, plus property rent, house cost and hotel cost; then the loan interest rate."]),
   ("currentMarketValue", "int currentMarketValue(GameState game[], int propIndex)",
   "The real worth of a property: purchase price minus age depreciation, times every applicable value modifier (global, group, rail, index).",
   [("propIndex", "The square.")],
   "Value in LKR.",
   [("price", "Working price."),
    ("depreciation", "Age depreciation percent."),
    ("mult", "Combined modifier multiplier.")],
   ["Base = purchasePrice x (100 - depreciation)/100.",
    "Mult accumulates MOD_VALUE_GLOBAL, then MOD_GROUP_VALUE (property), MOD_RAIL_VALUE (railway), then MOD_INDEX_VALUE (this square).",
    "Reused by buying, insurance, repairs, auctions, net worth - the single source of truth for prices."]),
   ("ageProperties", "void ageProperties(GameState game[])",
   "Rule-LK 15/16: ages every property; past age 50 depreciation ticks +5% every 5 rounds, capped at 30%, printing when it changes.",
   [], "void.",
   [("i", "Board index."),
    ("roundsOver50", "Age above the limit."),
    ("newDepreciation", "Computed depreciation."),
    ("oldDepreciation", "Previous value.")],
   ["Depreciation = roundsOver50 / 5, capped at MAX_DEPRECIATION (30)."]),
   ("tryRenovateAgeDepreciation", "void tryRenovateAgeDepreciation(GameState game[], int playerIndex, int propIndex)",
   "Rule-LK 17: landing on your own aged property offers a renovation - 10% of value, resetting age/depreciation and raising base rent +5%.",
   [("playerIndex", "The owner."),
    ("propIndex", "The property.")],
   "void.",
   [("cost", "Renovation cost.")],
   ["Only if there is depreciation, the strategy agrees, and the player can afford it."]),
   ("rentConditionPercent", "int rentConditionPercent(int condition)",
   "Table 3: maps building condition to the fraction of rent collected.",
   [("condition", "0..100.")],
   "Percent (0, 50, 75, 90 or 100).",
   [("(none)", "Branches on thresholds.")],
   [">=90 -> 100%, >=75 -> 90, >=50 -> 75, >=25 -> 50, else 0 (closed)."]),
   ("ageBuildings", "void ageBuildings(GameState game[])",
   "Rule-LK 25/28: condition drops 2 per round; lost-income countdown runs; 20+ rounds without maintenance causes structural damage (-15% value, -25% rent, 150% repairs).",
   [], "void.",
   [("i", "Board index.")],
   ["Business Interruption countdown decrements even for undeveloped properties (a hotel exists).",
    "On structural damage: stores pre-damage price/rent, applies losses, sets the cost multiplier to 150% and condition to 0."]),
   ("performMaintenance", "void performMaintenance(GameState game[], int playerIndex)",
   "Rule-LK 27: restores a building's condition to 100% for a fee (hotel 8%, house 5%), if the strategy agrees.",
   [("playerIndex", "The owner.")],
   "void.",
   [("i", "Board index."),
    ("baseCost", "Percent of building cost."),
    ("cost", "Cost x maintenance multiplier.")],
   ["Skips undeveloped, structurally damaged or condition-100 buildings; resets roundsSinceMaintenance."]),
   ("renovateStructuralDamage", "void renovateStructuralDamage(GameState game[], int playerIndex)",
   "Rule-LK 29: fully restores a structurally damaged building at 150% of replacement value, restoring pre-damage price/rent.",
   [("playerIndex", "The owner.")],
   "void.",
   [("i", "Board index."),
    ("replacementValue", "Hotel or house cost."),
    ("cost", "150% of replacement value.")],
   ["Restores preDamagePurchasePrice/preDamageBaseRent, condition 100, multiplier 100, clears the damage flag."]),
]),

# ============================ insurance.c ============================
("insurance.c",
 "Policies, disasters and repairs. Insurance squares sell policies whose type decides coverage and compensation; triggerDisaster runs the damage flow every 10 rounds.",
 [("propertyValue", "int propertyValue(GameState game[], int propIndex)",
   "A property's value = currentMarketValue.",
   [("propIndex", "The square.")],
   "Value in LKR.",
   [("(none)", "Delegates.")],
   ["Simple alias so insurance code reads naturally."]),
   ("repairCost", "int repairCost(GameState game[], int propIndex)",
   "Assumption: repairs cost 30% of a property's value.",
   [("propIndex", "The square.")],
   "Cost in LKR.",
   [("(none)", "Uses REPAIR_COST_PERCENT.")],
   ["= propertyValue x 30 / 100, used consistently everywhere repair cost is needed."]),
   ("isCovered", "int isCovered(InsuranceType policy, DisasterType disaster)",
   "Whether a policy covers a disaster type.",
   [("policy", "Held policy."),
    ("disaster", "The type that happened.")],
   "1 = covered, 0 = not.",
   [("(none)", "Branches on policy.")],
   ["Basic covers only Fire + Flood; Comprehensive and Business Interruption cover everything."]),
   ("compensationPercent", "int compensationPercent(InsuranceType policy)",
   "What fraction of the repair cost a policy pays.",
   [("policy", "Held policy.")],
   "Percent (0, 80 or 100).",
   [("(none)", "")],
   ["Basic 80%; Comprehensive and Business Interruption 100%."]),
   ("pickDisaster", "DisasterType pickDisaster(GameState game[])",
   "Weighted random disaster draw; all five start at weight 20, and active flood/riot risks add +30.",
   [], "DisasterType.",
   [("weights", "Per-type weight."),
    ("total", "Sum of weights."),
    ("i", "Index."),
    ("roll", "rand() % total."),
    ("result", "Chosen type.")],
   ["Heavy Monsoon -> flood more likely; Political Unrest -> riot more likely (Rule-LK 34)."]),
   ("purchaseInsurance", "void purchaseInsurance(GameState game[], int playerIndex, int propIndex, InsuranceType type)",
   "Buys a policy: premium = value x 5/10/15% x insurance modifier; policy lasts 20 rounds.",
   [("playerIndex", "The buyer."),
    ("propIndex", "The property."),
    ("type", "Policy to buy.")],
   "void.",
   [("value", "Property value."),
    ("premium", "Computed premium."),
    ("premiumPercent", "Type's rate."),
    ("premiumBuf", "Formatted premium.")],
   ["Only buys if affordable; sets insurance and insuranceRoundsLeft = 20."]),
   ("findPropertyToInsure", "int findPropertyToInsure(GameState game[], int playerIndex)",
   "Finds the first owned, uninsured property the strategy actually wants to insure.",
   [], "Square index, or -1.",
   [("i", "Board index.")],
   ["Any owned property can be insured (Section 2.8), developed or not - as long as desiredInsurance != NO_INSURANCE."]),
   ("findPropertyToRenew", "int findPropertyToRenew(GameState game[], int playerIndex)",
   "Finds a policy close to expiring (<= 10 rounds left) for renewal.",
   [], "Square index, or -1.",
   [("i", "Board index.")],
   ["Returns the first insured property under INSURANCE_RENEW_AT."]),
   ("handleInsuranceVisit", "void handleInsuranceVisit(GameState game[], int playerIndex)",
   "The Insurance square: renew an expiring policy first, otherwise buy a new one per the strategy.",
   [("playerIndex", "The visitor.")],
   "void.",
   [("propIndex", "Chosen property."),
    ("type", "Policy type.")],
   ["Renewal re-buys the same type for a fresh 20 rounds."]),
   ("tryAutoRepair", "void tryAutoRepair(GameState game[], int playerIndex)",
   "Rule-LK 11: at the start of a turn, repairs any disaster-damaged building the owner can afford.",
   [("playerIndex", "The player.")],
   "void.",
   [("i", "Board index."),
    ("cost", "repairCostOwed."),
    ("costBuf", "Formatted cost.")],
   ["Pays repairCostOwed, clears damaged/repairCostOwed so rent resumes."]),
   ("disasterName", "void disasterName(DisasterType disaster, char out[])",
   "Writes the human name of a disaster into out.",
   [("disaster", "The disaster type."),
    ("out", "Destination buffer.")],
   "void.",
   [("(none)", "")],
   ["Fire/Flood/Riot/Building Collapse/Electrical Failure."]),
   ("payCompensation", "int payCompensation(GameState game[], int chosen, int owner, int cost)",
   "Pays the insured owner compensation (80%/100%), inflating BI claims x150% during Political Unrest, and sets 5 rounds of lost income for BI policies.",
   [("chosen", "Damaged square."),
    ("owner", "The owner."),
    ("cost", "Repair cost.")],
   "Compensation actually paid.",
   [("compensation", "Raw compensation.")],
   ["BI policies also set lostIncomeRoundsLeft = 5 (still no rent for 5 rounds)."]),
   ("triggerDisaster", "void triggerDisaster(GameState game[])",
   "Rule-LK 10: every 10 rounds picks a random developed property and a disaster; insured owners get compensation, uninsured owners are marked sufferedLoss and own the full repair cost.",
   [], "void.",
   [("developed", "Indices of developed properties."),
    ("developedCount", "Their count."),
    ("i", "Board index."),
    ("chosen", "Struck property."),
    ("disaster", "Chosen disaster."),
    ("owner", "Its owner."),
    ("cost", "Repair cost."),
    ("compensation", "Insurance payout."),
    ("name", "Disaster name.")],
   ["If no developed property exists, nothing happens.",
    "Uninsured loss sets sufferedLoss = 1 - which flips the Risk Taker's strategy to wanting insurance.",
    "repairCostOwed = cost - compensation (clamped >= 0); if > 0 the property is damaged (no rent) until auto-repaired."]),
   ("processInsuranceExpiry", "void processInsuranceExpiry(GameState game[])",
   "Counts every policy down each round; warns at 3 rounds and expires (removes) at 0.",
   [], "void.",
   [("i", "Board index.")],
   ["Only affects properties holding a policy."]),
]),

# ============================ market.c ============================
("market.c",
 "The property market: boom/decline reviews every 10 rounds, regional development cards every 15 rounds, and the Rule-LK 36 market conditions report.",
 [("initMarket", "void initMarket(GameState game[])",
   "Resets market state: all group cooldowns 0, no last boom/decline.",
   [], "void.",
   [("i", "Group index.")],
   ["Set by startGame right after board/players/economy initialization."]),
   ("groupName", "void groupName(PropertyGroup group, char buffer[])",
   "Writes the display name of a colour group.",
   [("group", "The group."),
    ("buffer", "Destination.")],
   "void.",
   [("(none)", "")],
   ["Handles all 8 real groups plus Unknown."]),
   ("pickEligibleGroup", "PropertyGroup pickEligibleGroup(GameState game[], int currentRound, int avoid1, int avoid2)",
   "Picks a random group not on cooldown and not the groups to avoid.",
   [("currentRound", "For cooldown comparison."),
    ("avoid1", "Group to avoid (or -1)."),
    ("avoid2", "Second group to avoid (or -1).")],
   "PropertyGroup.",
   [("candidates", "Eligible groups."),
    ("count", "Their count."),
    ("g", "Loop index.")],
   ["Fallback when nothing eligible: (avoid1 + 1) % NO_GROUP, a rare defensive path."]),
   ("reviewPropertyMarket", "void reviewPropertyMarket(GameState game[], int currentRound)",
   "Rule-LK 30-34: one group booms (+20% value, +25% rent, +15% mortgage/purchase, +10% construction) and a different one declines (-15% value, -20% rent, -10% mortgage, -25% auction), each for 10 rounds.",
   [("currentRound", "Round number for cooldowns.")],
   "void.",
   [("boomGroup", "Chosen boom group."),
    ("declineGroup", "Chosen decline group."),
    ("boomName, declineName", "Formatted names.")],
   ["All effects are temporary sourced modifiers (SRC_BOOM / SRC_DECLINE) - no base value is ever changed.",
    "Sets both groups' cooldowns to currentRound + 30 and remembers the last picks so they can't repeat."]),
   ("drawRegionalCard", "void drawRegionalCard(GameState game[])",
   "Table 4: one of 12 regional development cards every 15 rounds, active for 15, all as SRC_REGIONAL modifiers.",
   [], "void.",
   [("choice", "rand() % 12.")],
   ["Cards boost or cut province values/rents (Southern Tourism, Port City, IT Industry, Northern Programme, Tea Boom, Airport, University, Beach Pollution, Flooding, Transport Strike, Electricity Tariff, Water Shortage).",
    "Some cards also add per-index modifiers (e.g. Colombo Fort station, tea-export square, water squares)."]),
   ("printSectionHeader", "void printSectionHeader(char title[])",
   "Prints a report section title and separator.",
   [("title", "Heading text.")],
   "void.",
   [("(none)", "")],
   ["Small formatting helper used by the conditions report."]),
   ("printBoomDecline", "void printBoomDecline(char title[], char groupNameBuffer[], int percent, int roundsLeft)",
   "Prints one Market Boom / Market Decline block.",
   [("title", "Boom or Decline."),
    ("groupNameBuffer", "Group name."),
    ("percent", "Value multiplier."),
    ("roundsLeft", "Rounds remaining.")],
   "void.",
   [("(none)", "")],
   ["Shows the signed percent (percent - 100) and the time left."]),
   ("describeRegionalCondition", "int describeRegionalCondition(GameState game[], ActiveModifier mod, char out[])",
   "Writes one regional card effect line; returns 1 if a line was produced.",
   [("mod", "A modifier."),
    ("out", "Destination.")],
   "1 = wrote a line, 0 = not a printable type.",
   [("name", "Group or square name.")],
   ["Handles group value/rent, index value, rail and utility rent. Called for every SRC_REGIONAL modifier."]),
   ("printRegionalSection", "int printRegionalSection(GameState game[])",
   "Prints all active Regional Development effects under one header.",
   [], "1 if anything was printed.",
   [("i", "Modifier index."),
    ("shown", "Whether the header was printed."),
    ("mod", "Current modifier."),
    ("line", "Formatted line.")],
   ["Collects SRC_REGIONAL modifiers with a printable describeRegionalCondition."]),
   ("describeOtherCondition", "int describeOtherCondition(GameState game[], ActiveModifier mod, char out[])",
   "Writes one 'Other Active Conditions' line; returns 1 if written.",
   [("mod", "A modifier."),
    ("out", "Destination.")],
   "1 = wrote a line, 0 = not printable.",
   [("name", "Group or square name.")],
   ["Handles group value/rent, index value, rail value/rent and utility rent."]),
   ("printOtherConditions", "void printOtherConditions(GameState game[])",
   "Prints still-running event/regulation (SRC_GENERAL) modifiers.",
   [], "void.",
   [("i", "Modifier index."),
    ("shown", "Header printed flag."),
    ("mod", "Current modifier."),
    ("line", "Formatted line.")],
   ["Used at the end of the market report."]),
   ("displayMarketConditions", "void displayMarketConditions(GameState game[])",
   "Rule-LK 36: the end-of-round market report - boom, decline, regional development, other conditions, inflation, loan interest and tax rate.",
   [], "void.",
   [("i", "Modifier index."),
    ("shown", "Whether anything was printed."),
    ("name", "Group name.")],
   ["Picks the boom and decline from SRC_BOOM/SRC_DECLINE MOD_GROUP_VALUE modifiers, prints regional + other sections, then inflation/interest/tax always."]),
]),

# ============================ main.c ============================
("main.c",
 "The entry point. Creates the single GameState and hands control to startGame.",
 [("main", "int main(void)",
   "The only place a GameState is ever created (game[1] = {0}), then startGame runs the whole simulation.",
   [], "0 on success.",
   [("game", "The single GameState (array-of-one idiom).")],
   ["Prints the banner, then calls startGame(game).",
    "The array-of-one idiom means every function receives a pointer that is used with plain array syntax (game[0].field), avoiding pointer arithmetic."]),
]),
]